export const jackets = [
    {
        img: "jacket1.png",
        alt: "XM xtreme GTX. Black rain jacket.",
        manufactor: "XM",
        model: "xtreme GTX",
        price: 99.99,
        stars: 3.8,
        color: ["grey"],
        sizes: ["XS","S", "M", "L", "XL", "XXL"],
        gender: ["male", "female", "unisex"],
    }, 
    {
        img: "jacket2.png",
        alt: "Scott Terrain Dryo. Grey rain jacket.",
        manufactor: "Scott",
        model: "Terrain Dryo",
        price: 199.99,
        stars: 5,
        color: ["grey"],
        sizes: ["XS","S", "M", "L", "XL", "XXL"],
        gender: ["male", "female", "unisex"],
    },
    {
        img: "jacket3.png",
        alt: "Craft Rainy Run. Red rain jacket.",
        manufactor: "Craft",
        model: "Rainy Run",
        price: 199.99,
        stars: 4.4,
        color: ["red"],
        sizes: ["XS","S", "M", "L", "XL", "XXL"],
        gender: ["male", "female", "unisex"],
    },
    {
        img: "jacket4.png",
        alt: "Stormberg Boat. Grey and orange rain jacket.",
        manufactor: "Stormberg",
        model: "Boat",
        price: 99.99,
        stars: 4.5,
        color: ["grey", "orange"],
        sizes: ["XS","S", "M", "L", "XL", "XXL"],
        gender: ["male", "female", "unisex"],
    },
    {
        img: "jacket5.png",
        alt: "Rainydays Rain. Grey rain jacket.",
        manufactor: "RAINYDAYS",
        model: "Rain",
        price: 199.99,
        stars: 4.5,
        color: ["grey"],
        sizes: ["XS","S", "M", "L", "XL", "XXL"],
        gender: ["male", "female", "unisex"],
    },
    {
        img: "jacket6.png",
        alt: "RainWomen. Pink rainjacket.",
        manufactor: "RainWomen",
        model: "Flower",
        price: 129.99,
        stars: 4.8,
        color: ["pink"],
        sizes: ["XS","S", "M", "L", "XL", "XXL"],
        gender: ["female"],
    },
]